
import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import BN from "bn.js";
import {
  PublicKey,
  Keypair,
  SystemProgram,
  Transaction,
  sendAndConfirmTransaction,
} from "@solana/web3.js";
import * as fs from "fs";
import * as path from "path";


import dotenv from "dotenv";
dotenv.config({path: path.join(process.cwd(), ".env")});

// Load IDL from target (generated by anchor build). Use process.cwd() when run from anchor/
const idlPath = path.join(process.cwd(), "tests/order_executor.json");
const idl = JSON.parse(fs.readFileSync(idlPath, "utf8"));

/** Helper: init user counter + create order with 1 SOL transfer to recipient. Returns PDAs. Reusable across test files. */
export async function createOrderWithTransferSetup(
  program: Program,
  user: Keypair,
  recipient: PublicKey,
  lamportsPerSol: bigint
) {
  const [orderCounterPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("order_counter"), user.publicKey.toBuffer()],
    program.programId
  );

  const [orderPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("order"), user.publicKey.toBuffer(), Buffer.alloc(8, 0)],
    program.programId
  );

  const [vaultPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("vault"), user.publicKey.toBuffer(), Buffer.alloc(8, 0)],
    program.programId
  );

  await program.methods
    .initUserCounter()
    .accounts({
      user: user.publicKey,
      orderCounter: orderCounterPda,
      systemProgram: SystemProgram.programId,
    })
    .signers([user])
    .rpc();

  const inputAmount = new BN((2n * lamportsPerSol).toString());
  const executionBounty = new BN(10_000_000);
  const trigger = { timeAfter: { slot: new BN(402716150) } };
  const transferIx = SystemProgram.transfer({
    fromPubkey: vaultPda,
    toPubkey: recipient,
    lamports: Number(lamportsPerSol),
  });
  const action = {
    cpi: {
      programId: SystemProgram.programId,
      accounts: [
        { pubkey: vaultPda, isWritable: true },
        { pubkey: recipient, isWritable: true },
      ],
      data: Buffer.from(transferIx.data),
    },
  };

  await program.methods
    .createOrder(inputAmount, trigger, action, null, executionBounty)
    .accounts({
      user: user.publicKey,
      orderCounter: orderCounterPda,
      order: orderPda,
      vault: vaultPda,
      systemProgram: SystemProgram.programId,
    })
    .signers([user])
    .rpc();

  return { orderCounterPda, orderPda, vaultPda };
}

/** Stork feed_ids (Keccak256 from Stork Asset ID Registry). */
const BTCUSD_FEED_ID = Buffer.from(
  "7404e3d104ea7841c3d9e6fd20adfe99b4ad586bc08d8f3bd3afef894cf184de",
  "hex"
);
const USDTUSD_FEED_ID = Buffer.from(
  "6dcd0a8fb0460d4f0f98c524e06c10c63377cd098b589c0b90314bfb55751558",
  "hex"
);
const YZYUSDMARK_FEED_ID = Buffer.from(
  "041aca5a7fa22cfc954a9e14026f5d96d6b18a89043ffcda04a9535525148ea6",
  "hex"
);

/**
 * Create an order with PriceAboveStork trigger for BTCUSD.
 * - feed_id: BTCUSD (from Stork Asset ID Registry)
 * - min_price_q: $60,000 (60_000_000_000 = 60k with 6 decimals)
 * - max_age_sec: 300 (5 minutes)
 */
export async function createOrderWithPriceAboveStorkBtcUsd(
  program: Program,
  user: Keypair,
  recipient: PublicKey,
  orderCounterPda: PublicKey,
  lamportsPerSol: bigint,
  orderId: bigint = 0n
) {
  const orderIdBuf = Buffer.alloc(8);
  orderIdBuf.writeBigUInt64LE(orderId);
  const [orderPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("order"), user.publicKey.toBuffer(), orderIdBuf],
    program.programId
  );
  const [vaultPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("vault"), user.publicKey.toBuffer(), orderIdBuf],
    program.programId
  );

  const inputAmount = new BN((2n * lamportsPerSol).toString());
  const executionBounty = new BN(10_000_000);
  const trigger = {
    priceAboveStork: {
      feedId: Array.from(BTCUSD_FEED_ID),
      minPriceQ: new BN("60000000000"),
      maxAgeSec: new BN(300),
    },
  };
  const transferIx = SystemProgram.transfer({
    fromPubkey: vaultPda,
    toPubkey: recipient,
    lamports: Number(lamportsPerSol),
  });
  const action = {
    cpi: {
      programId: SystemProgram.programId,
      accounts: [
        { pubkey: vaultPda, isWritable: true },
        { pubkey: recipient, isWritable: true },
      ],
      data: Buffer.from(transferIx.data),
    },
  };

  await program.methods
    .createOrder(inputAmount, trigger, action, null, executionBounty)
    .accounts({
      user: user.publicKey,
      orderCounter: orderCounterPda,
      order: orderPda,
      vault: vaultPda,
      systemProgram: SystemProgram.programId,
    })
    .signers([user])
    .rpc();

  return { orderPda, vaultPda };
}

/**
 * Create order with StorkOutcomeEquals trigger. Executes when feed value equals expectedOutcomeQ.
 * @param expectedOutcomeQ - Quantized value (e.g. 1_000_000 for $1 with 6 decimals)
 */
export async function createOrderWithStorkOutcomeEquals(
  program: Program,
  user: Keypair,
  recipient: PublicKey,
  orderCounterPda: PublicKey,
  feedId: Buffer,
  expectedOutcomeQ: bigint,
  lamportsPerSol: bigint,
  orderId: bigint,
  maxAgeSec: number = 300
) {
  const orderIdBuf = Buffer.alloc(8);
  orderIdBuf.writeBigUInt64LE(orderId);
  const [orderPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("order"), user.publicKey.toBuffer(), orderIdBuf],
    program.programId
  );
  const [vaultPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("vault"), user.publicKey.toBuffer(), orderIdBuf],
    program.programId
  );

  const inputAmount = new BN((2n * lamportsPerSol).toString());
  const executionBounty = new BN(10_000_000);
  const trigger = {
    storkOutcomeEquals: {
      feedId: Array.from(feedId),
      expectedOutcomeQ: new BN(expectedOutcomeQ.toString()),
      maxAgeSec: new BN(maxAgeSec),
    },
  };
  const transferIx = SystemProgram.transfer({
    fromPubkey: vaultPda,
    toPubkey: recipient,
    lamports: Number(lamportsPerSol),
  });
  const action = {
    cpi: {
      programId: SystemProgram.programId,
      accounts: [
        { pubkey: vaultPda, isWritable: true },
        { pubkey: recipient, isWritable: true },
      ],
      data: Buffer.from(transferIx.data),
    },
  };

  await program.methods
    .createOrder(inputAmount, trigger, action, null, executionBounty)
    .accounts({
      user: user.publicKey,
      orderCounter: orderCounterPda,
      order: orderPda,
      vault: vaultPda,
      systemProgram: SystemProgram.programId,
    })
    .signers([user])
    .rpc();

  return { orderPda, vaultPda };
}

const provider = anchor.AnchorProvider.env();
anchor.setProvider(provider);
const program = new Program({ ...idl, address: new PublicKey(process.env.PROGRAM_ID!) }, provider);

const user = Keypair.generate();
const LAMPORTS_PER_SOL = 1_000_000_000n;

for (const pubkey of [user.publicKey, provider.wallet.publicKey]) {
    // 1. Get latest blockhash context
    const latestBlockHash = await provider.connection.getLatestBlockhash();

    // 2. Request airdrop
    const sig = await provider.connection.requestAirdrop(
        pubkey,
        10 * Number(LAMPORTS_PER_SOL)
    );

    // 3. Confirm using the strategy object
    await provider.connection.confirmTransaction({
        signature: sig,
        blockhash: latestBlockHash.blockhash,
        lastValidBlockHeight: latestBlockHash.lastValidBlockHeight,
    });
}

let orderPda: PublicKey;
let orderCounterPda: PublicKey;
let vaultPda: PublicKey;
const recipient = provider.wallet.publicKey;

function test1() {
    return new Promise(async (resolve, reject) => {
        try {
            const pdas = await createOrderWithTransferSetup(
                program,
                user,
                recipient,
                LAMPORTS_PER_SOL
            );

        
            orderPda = pdas.orderPda;
            orderCounterPda = pdas.orderCounterPda;
            vaultPda = pdas.vaultPda;
            console.log("Order created successfully");
            console.log("Order PDA:", orderPda.toBase58());
            console.log("Order Counter PDA:", orderCounterPda.toBase58());
            console.log("Vault PDA:", vaultPda.toBase58());
            const vaultAccount = await provider.connection.getAccountInfo(vaultPda);
            const vaultBalance = vaultAccount ? vaultAccount.lamports : 0;
            console.log("Vault balance (SOL):", vaultBalance / Number(LAMPORTS_PER_SOL));

            resolve(true);
        } catch (error) {
            reject(error);
        }
    });
}





function test2() {
  return new Promise(async (resolve, reject) => {
    try {
      const pdas = await createOrderWithPriceAboveStorkBtcUsd(
        program,
        user,
        recipient,
        orderCounterPda,
        LAMPORTS_PER_SOL,
        1n
      );

      console.log("Test 2: Order with PriceAboveStork BTCUSD created");
      console.log("Order PDA:", pdas.orderPda.toBase58());
      console.log("Vault PDA:", pdas.vaultPda.toBase58());

      resolve(true);
    } catch (error) {
      reject(error);
    }
  });
}

/** Test 3: StorkOutcomeEquals order - 1 SOL to recipient when YZYUSDMARK equals expected value. */
function test3() {
  return new Promise(async (resolve, reject) => {
    try {
      const pdas = await createOrderWithStorkOutcomeEquals(
        program,
        user,
        recipient,
        orderCounterPda,
        YZYUSDMARK_FEED_ID,
        330243395000000000n, // Set from Stork REST API for YZYUSDMARK
        LAMPORTS_PER_SOL,
        2n
      );
      console.log("Test 3: Order with StorkOutcomeEquals YZYUSDMARK created");
      console.log("Order PDA:", pdas.orderPda.toBase58());
      console.log("Vault PDA:", pdas.vaultPda.toBase58());
      resolve(true);
    } catch (error) {
      reject(error);
    }
  });
}

test1()
  .then((result) => {
    console.log("Test 1 passed:", result);
    return test2();
  })
  .then((result) => {
    console.log("Test 2 passed:", result);
    return test3();
  })
  .then((result) => {
    console.log("Test 3 passed:", result);
  })
  .catch((error) => {
    console.error("Test error:", error);
  });


// test3().then((result) => {
//   console.log("Test 3 passed:", result);
// }).catch((error) => {
//   console.error("Test error:", error);
// });