import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import BN from "bn.js";
import {
  PublicKey,
  Keypair,
  SystemProgram,
  Transaction,
  sendAndConfirmTransaction,
} from "@solana/web3.js";
import { expect } from "chai";
import * as fs from "fs";
import * as path from "path";
// Load IDL from target (generated by anchor build). Use process.cwd() when run from anchor/
const idlPath = path.join(process.cwd(), "target/idl/order_executor.json");
const idl = JSON.parse(fs.readFileSync(idlPath, "utf8"));
const anchorTomlPath = path.join(process.cwd(), "Anchor.toml");

/** Helper: init user counter + create order with 1 SOL transfer to recipient. Returns PDAs. Reusable across test files. */
export async function createOrderWithTransferSetup(
  program: Program,
  user: Keypair,
  recipient: PublicKey,
  lamportsPerSol: bigint
) {
  const [orderCounterPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("order_counter"), user.publicKey.toBuffer()],
    program.programId
  );

  const [orderPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("order"), user.publicKey.toBuffer(), Buffer.alloc(8, 0)],
    program.programId
  );

  const [vaultPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("vault"), user.publicKey.toBuffer(), Buffer.alloc(8, 0)],
    program.programId
  );

  await program.methods
    .initUserCounter()
    .accounts({
      user: user.publicKey,
      orderCounter: orderCounterPda,
      systemProgram: SystemProgram.programId,
    })
    .signers([user])
    .rpc();

  const inputAmount = new BN((2n * lamportsPerSol).toString());
  const executionBounty = new BN(10_000_000);
  const trigger = { timeAfter: { slot: new BN(0) } };
  const transferIx = SystemProgram.transfer({
    fromPubkey: vaultPda,
    toPubkey: recipient,
    lamports: Number(lamportsPerSol),
  });
  const action = {
    cpi: {
      programId: SystemProgram.programId,
      accounts: [
        { pubkey: vaultPda, isWritable: true },
        { pubkey: recipient, isWritable: true },
      ],
      data: Buffer.from(transferIx.data),
    },
  };

  await program.methods
    .createOrder(inputAmount, trigger, action, null, executionBounty)
    .accounts({
      user: user.publicKey,
      orderCounter: orderCounterPda,
      order: orderPda,
      vault: vaultPda,
      systemProgram: SystemProgram.programId,
    })
    .signers([user])
    .rpc();

  return { orderCounterPda, orderPda, vaultPda };
}

/** Create an order without init (user must already have order_counter). Use for order_id 1, 2, etc. */
async function createOrderOnly(
  program: Program,
  user: Keypair,
  recipient: PublicKey,
  orderCounterPda: PublicKey,
  lamportsPerSol: bigint
) {
  const orderId1 = Buffer.alloc(8);
  orderId1.writeBigUInt64LE(1n);
  const [orderPda1] = PublicKey.findProgramAddressSync(
    [Buffer.from("order"), user.publicKey.toBuffer(), orderId1],
    program.programId
  );
  const [vaultPda1] = PublicKey.findProgramAddressSync(
    [Buffer.from("vault"), user.publicKey.toBuffer(), orderId1],
    program.programId
  );

  const inputAmount = new BN((2n * lamportsPerSol).toString());
  const executionBounty = new BN(10_000_000);
  const trigger = { timeAfter: { slot: new BN(0) } };
  const transferIx = SystemProgram.transfer({
    fromPubkey: vaultPda1,
    toPubkey: recipient,
    lamports: Number(lamportsPerSol),
  });
  const action = {
    cpi: {
      programId: SystemProgram.programId,
      accounts: [
        { pubkey: vaultPda1, isWritable: true },
        { pubkey: recipient, isWritable: true },
      ],
      data: Buffer.from(transferIx.data),
    },
  };

  await program.methods
    .createOrder(inputAmount, trigger, action, null, executionBounty)
    .accounts({
      user: user.publicKey,
      orderCounter: orderCounterPda,
      order: orderPda1,
      vault: vaultPda1,
      systemProgram: SystemProgram.programId,
    })
    .signers([user])
    .rpc();

  return { orderPda: orderPda1, vaultPda: vaultPda1 };
}

describe("order_executor", function () {
  this.timeout(30_000); // RPC calls (airdrop, confirm) can take several seconds

  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);
  const resolvedProgramId = resolveOrderExecutorProgramId(provider.connection.rpcEndpoint);
  const program = new Program({ ...idl, address: resolvedProgramId.toBase58() }, provider);

  const user = Keypair.generate();
  const LAMPORTS_PER_SOL = 1_000_000_000n;

  before(async () => {
    // Airdrop SOL to user and provider wallet for transactions
    for (const pubkey of [user.publicKey, provider.wallet.publicKey]) {
      // 1. Get latest blockhash context
      const latestBlockHash = await provider.connection.getLatestBlockhash();
      
      // 2. Request airdrop
      const sig = await provider.connection.requestAirdrop(
        pubkey,
        10 * Number(LAMPORTS_PER_SOL)
      );

      // 3. Confirm using the strategy object
      await provider.connection.confirmTransaction({
        signature: sig,
        blockhash: latestBlockHash.blockhash,
        lastValidBlockHeight: latestBlockHash.lastValidBlockHeight,
      });
    }
  });

  let orderPda: PublicKey;
  let orderCounterPda: PublicKey;
  let vaultPda: PublicKey;

  // create the order with cpi transfer of 1 SOL to the default solana pubkey
  before(async () => {
    const recipient = provider.wallet.publicKey;
    const pdas = await createOrderWithTransferSetup(
      program,
      user,
      recipient,
      LAMPORTS_PER_SOL
    );
    orderPda = pdas.orderPda;
    orderCounterPda = pdas.orderCounterPda;
    vaultPda = pdas.vaultPda;
  });

  describe("create_order", () => {
    it("initializes user counter and creates order successfully", async () => {
      // Verify order account (setup ran in before)
      const orderAccount = await (program.account as any).order.fetch(orderPda);
      expect(orderAccount.user.equals(user.publicKey)).to.be.true;
      expect(orderAccount.orderId.toNumber()).to.equal(0);
      expect(orderAccount.inputAmount.toString()).to.equal(
        (2n * LAMPORTS_PER_SOL).toString()
      );
      expect(orderAccount.executed).to.be.false;
      expect(orderAccount.canceled).to.be.false;

      // Verify vault has lamports
      const vaultAccount = await provider.connection.getAccountInfo(vaultPda);
      expect(vaultAccount).to.not.be.null;
      expect(vaultAccount!.lamports).to.be.at.least(Number(2n * LAMPORTS_PER_SOL));

      // Verify counter incremented
      const counterAccount = await (
        program.account as any
      ).userOrderCounter.fetch(orderCounterPda);
      expect(counterAccount.nextOrderId.toNumber()).to.equal(1);
      expect(counterAccount.openOrderCount.toNumber()).to.equal(1);
    });
  });

  // create the keeper account

  let keeper: Keypair;
  let latestBlockHash: any;

  before(async () => {
    // create the keeper account before tests run
    latestBlockHash = await provider.connection.getLatestBlockhash();
    keeper = Keypair.generate();
    const sig = await provider.connection.requestAirdrop(
      keeper.publicKey,
      10 * Number(LAMPORTS_PER_SOL)
    );
    await provider.connection.confirmTransaction({
      signature: sig,
      blockhash: latestBlockHash.blockhash,
      lastValidBlockHeight: latestBlockHash.lastValidBlockHeight,
    });
  });
 

  describe("execute_order_if_ready", () => {
    it("executes order if ready successfully", async () => {
      
      const recipient = provider.wallet.publicKey;
      const recipientBalanceBefore = await provider.connection.getBalance(recipient);
      console.log("recipient (CLI wallet) balance before", recipientBalanceBefore);


      const keeperBalanceBefore = await provider.connection.getBalance(keeper.publicKey);
      console.log("keeper balance", keeperBalanceBefore);
      expect(keeperBalanceBefore).to.equal(10 * Number(LAMPORTS_PER_SOL));

      // orderPda, vaultPda from shared before hook (createOrderWithTransferSetup)
      // check the vault balance (2 SOL + rent-exempt min for 0-byte account ~890880)
      const vaultBalance = await provider.connection.getBalance(vaultPda);
      console.log("vault balance", vaultBalance);
      const expectedVaultBalance = Number(2n * LAMPORTS_PER_SOL) + 890880; // 2 SOL + rent
      expect(vaultBalance).to.equal(expectedVaultBalance);

      // CPI remaining_accounts: [vault, recipient, system_program] per CpiAction layout
      // User pays the tx fee (not recipient); build tx with user as fee payer
      const executeIx = await program.methods
        .executeOrderIfReady(null)
        .accounts({
          order: orderPda,
          vault: vaultPda,
          user: user.publicKey,
          keeper: keeper.publicKey,
          pdaAccount: SystemProgram.programId, // placeholder for TimeAfter trigger
          systemProgram: SystemProgram.programId,
        })
        .remainingAccounts([
          { pubkey: vaultPda, isWritable: true, isSigner: false },
          { pubkey: provider.wallet.publicKey, isWritable: true, isSigner: false },
          { pubkey: SystemProgram.programId, isWritable: false, isSigner: false },
        ])
        .instruction();

      const tx = new Transaction().add(executeIx);
      tx.feePayer = user.publicKey;
      await sendAndConfirmTransaction(provider.connection, tx, [user, keeper], {
        preflightCommitment: "confirmed",
      });


      // verifications 

       
      // verify the order pda is in the right state
      const orderAccount = await (program.account as any).order.fetch(orderPda);
      // Log all fields from the order PDA account
      console.log("Order PDA fields:");
      console.log("user:", orderAccount.user.toBase58());
      console.log("order_id:", orderAccount.orderId?.toString());
      console.log("input_amount:", orderAccount.inputAmount?.toString());
      console.log("trigger:", orderAccount.trigger);
      console.log("action:", orderAccount.action);
      console.log("created_slot:", orderAccount.createdSlot?.toString());
      console.log("expires_slot:", orderAccount.expiresSlot ? orderAccount.expiresSlot.toString() : null);
      console.log("executed:", orderAccount.executed);
      console.log("canceled:", orderAccount.canceled);
      console.log("execution_bounty:", orderAccount.executionBounty?.toString());
      expect(orderAccount.executed).to.be.true;


      // verify vault decreased by 1 SOL (transfer) + execution bounty
      const vaultBalanceAfter = await provider.connection.getBalance(vaultPda);
      console.log("vault balance", vaultBalanceAfter);
      const bounty = Number(orderAccount.executionBounty?.toString() ?? 0);
      expect(vaultBalanceAfter).to.equal(vaultBalance - Number(LAMPORTS_PER_SOL) - bounty);

      // verify the recipient received exactly 1 SOL (user pays tx fee, not recipient)
      const recipientBalanceAfter = await provider.connection.getBalance(recipient);
      console.log("recipient (CLI wallet) balance after", recipientBalanceAfter);
      expect(recipientBalanceAfter).to.equal(recipientBalanceBefore + Number(LAMPORTS_PER_SOL));

      // verify the keeper balance has increased by the execution bounty
      const keeperBalanceAfter = await provider.connection.getBalance(keeper.publicKey);
      console.log("keeper balance after", keeperBalanceAfter);
      expect(keeperBalanceAfter).to.be.at.least(Number(keeperBalanceBefore) + Number(orderAccount.executionBounty?.toString()));

      
    });
  });



  describe("cancel_order", () => {
    // Create order 1 (order_counter already exists from root before; order 0 was created + executed)
    before(async () => {
      const recipient = provider.wallet.publicKey;
      const pdas = await createOrderOnly(
        program,
        user,
        recipient,
        orderCounterPda,
        LAMPORTS_PER_SOL
      );
      orderPda = pdas.orderPda;
      vaultPda = pdas.vaultPda;
    });
    
    // cancel the order with order id 1
    it("cancels order with order id 1 successfully", async () => {


      const userBalanceBefore = await provider.connection.getBalance(user.publicKey);
      console.log("user balance before", userBalanceBefore);


      // cancel the order with order id 1
      const cancelIx = await program.methods
        .cancelOrder(new BN(1))
        .accounts({
          order: orderPda,
          vault: vaultPda,
          user: user.publicKey,
        })
        .signers([user])
        .instruction();

      const tx = new Transaction().add(cancelIx);
      tx.feePayer = user.publicKey;
      await sendAndConfirmTransaction(provider.connection, tx, [user], {
        preflightCommitment: "confirmed",
      });

      // verify the order pda is in the right state
      const orderAccount = await (program.account as any).order.fetch(orderPda);
      expect(orderAccount.canceled).to.be.true;

      //verify the user balance has increased by more than 1 SOL (refund + tx fee)
      const userBalanceAfter = await provider.connection.getBalance(user.publicKey);
      console.log("user balance after", userBalanceAfter);
      expect(userBalanceAfter).to.be.at.least(userBalanceBefore + Number(LAMPORTS_PER_SOL));

    });
  });
});

function resolveOrderExecutorProgramId(rpcEndpoint: string): PublicKey {
  const anchorToml = fs.readFileSync(anchorTomlPath, "utf8");
  const targetSection = /127\.0\.0\.1|localhost/.test(rpcEndpoint) ? "localnet" : "devnet";
  const sectionMatch = anchorToml.match(
    new RegExp(
      String.raw`\[programs\.${targetSection}\][\s\S]*?order_executor\s*=\s*"([^"]+)"`,
      "m",
    ),
  );

  const fallback = (idl.address as string | undefined) ?? (idl.metadata?.address as string);
  const address = sectionMatch?.[1] ?? fallback;
  if (!address) {
    throw new Error("Could not resolve order_executor program id from Anchor.toml or IDL");
  }
  return new PublicKey(address);
}
