import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { PublicKey, Keypair, SystemProgram } from "@solana/web3.js";
import { expect } from "chai";
import * as fs from "fs";
import * as path from "path";
// Load IDL from target (generated by anchor build). Use process.cwd() when run from anchor/
const idlPath = path.join(process.cwd(), "target/idl/order_executor.json");
const idl = JSON.parse(fs.readFileSync(idlPath, "utf8"));

describe("order_executor", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = new Program(idl, provider);

  const user = Keypair.generate();
  const LAMPORTS_PER_SOL = 1_000_000_000n;

  before(async () => {
    // Airdrop SOL to user and provider wallet for transactions
    for (const pubkey of [user.publicKey, provider.wallet.publicKey]) {
      // 1. Get latest blockhash context
      const latestBlockHash = await provider.connection.getLatestBlockhash();
      
      // 2. Request airdrop
      const sig = await provider.connection.requestAirdrop(
        pubkey,
        10 * Number(LAMPORTS_PER_SOL)
      );

      // 3. Confirm using the strategy object
      await provider.connection.confirmTransaction({
        signature: sig,
        blockhash: latestBlockHash.blockhash,
        lastValidBlockHeight: latestBlockHash.lastValidBlockHeight,
      });
    }
  });

  describe("create_order", () => {
    it("initializes user counter and creates order successfully", async () => {
      const [orderCounterPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("order_counter"), user.publicKey.toBuffer()],
        program.programId
      );

      const [orderPda] = PublicKey.findProgramAddressSync(
        [
          Buffer.from("order"),
          user.publicKey.toBuffer(),
          Buffer.alloc(8, 0), // order_id 0
        ],
        program.programId
      );

      const [vaultPda] = PublicKey.findProgramAddressSync(
        [
          Buffer.from("vault"),
          user.publicKey.toBuffer(),
          Buffer.alloc(8, 0),
        ],
        program.programId
      );

      // 1. Init user counter
      await program.methods
        .initUserCounter()
        .accounts({
          user: user.publicKey,
          orderCounter: orderCounterPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([user])
        .rpc();

      const inputAmount = new anchor.BN(LAMPORTS_PER_SOL.toString());
      const executionBounty = new anchor.BN(10_000_000);

      // 2. Create order with TimeAfter trigger and system program action (no-op CPI)
      const trigger = {
        timeAfter: { slot: new anchor.BN(0) },
      };

      const action = {
        programId: SystemProgram.programId,
        accounts: [],
        data: Buffer.from([]),
      };

      await program.methods
        .createOrder(
          inputAmount,
          trigger,
          action,
          null, // expires_slot
          executionBounty
        )
        .accounts({
          user: user.publicKey,
          orderCounter: orderCounterPda,
          order: orderPda,
          vault: vaultPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([user])
        .rpc();

      // Verify order account
      const orderAccount = await (program.account as any).order.fetch(orderPda);
      expect(orderAccount.user.equals(user.publicKey)).to.be.true;
      expect(orderAccount.orderId.toNumber()).to.equal(0);
      expect(orderAccount.inputAmount.toString()).to.equal(
        LAMPORTS_PER_SOL.toString()
      );
      expect(orderAccount.executed).to.be.false;
      expect(orderAccount.canceled).to.be.false;

      // Verify vault has lamports
      const vaultAccount = await provider.connection.getAccountInfo(vaultPda);
      expect(vaultAccount).to.not.be.null;
      expect(vaultAccount!.lamports).to.be.at.least(Number(LAMPORTS_PER_SOL));

      // Verify counter incremented
      const counterAccount = await (
        program.account as any
      ).userOrderCounter.fetch(orderCounterPda);
      expect(counterAccount.nextOrderId.toNumber()).to.equal(1);
      expect(counterAccount.openOrderCount.toNumber()).to.equal(1);
    });
  });
});
