import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import BN from "bn.js";
import {
  PublicKey,
  Keypair,
  SystemProgram,
  Transaction,
  sendAndConfirmTransaction,
} from "@solana/web3.js";
import { expect } from "chai";
import * as fs from "fs";
import * as path from "path";
// Load IDL from target (generated by anchor build). Use process.cwd() when run from anchor/
const idlPath = path.join(process.cwd(), "target/idl/order_executor.json");
const idl = JSON.parse(fs.readFileSync(idlPath, "utf8"));

describe("order_executor", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = new Program(idl, provider);

  const user = Keypair.generate();
  const LAMPORTS_PER_SOL = 1_000_000_000n;

  before(async () => {
    // Airdrop SOL to user and provider wallet for transactions
    for (const pubkey of [user.publicKey, provider.wallet.publicKey]) {
      // 1. Get latest blockhash context
      const latestBlockHash = await provider.connection.getLatestBlockhash();
      
      // 2. Request airdrop
      const sig = await provider.connection.requestAirdrop(
        pubkey,
        10 * Number(LAMPORTS_PER_SOL)
      );

      // 3. Confirm using the strategy object
      await provider.connection.confirmTransaction({
        signature: sig,
        blockhash: latestBlockHash.blockhash,
        lastValidBlockHeight: latestBlockHash.lastValidBlockHeight,
      });
    }
  });

  describe("create_order", () => {
    it("initializes user counter and creates order successfully", async () => {
      const [orderCounterPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("order_counter"), user.publicKey.toBuffer()],
        program.programId
      );

      const [orderPda] = PublicKey.findProgramAddressSync(
        [
          Buffer.from("order"),
          user.publicKey.toBuffer(),
          Buffer.alloc(8, 0), // order_id 0
        ],
        program.programId
      );

      const [vaultPda] = PublicKey.findProgramAddressSync(
        [
          Buffer.from("vault"),
          user.publicKey.toBuffer(),
          Buffer.alloc(8, 0),
        ],
        program.programId
      );

      // 1. Init user counter
      await program.methods
        .initUserCounter()
        .accounts({
          user: user.publicKey,
          orderCounter: orderCounterPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([user])
        .rpc();

      // Need enough for: 1 SOL transfer + execution bounty
      const inputAmount = new BN((2n * LAMPORTS_PER_SOL).toString());
      const executionBounty = new BN(10_000_000);

      

      // 2. Create order with TimeAfter trigger and System Program transfer (1 SOL to recipient)
      const trigger = {
        timeAfter: { slot: new BN(0) },
      };

      // Recipient: Solana CLI config wallet (provider.wallet = ANCHOR_WALLET)
      const recipient = provider.wallet.publicKey;
      const transferAmount = LAMPORTS_PER_SOL; // 1 SOL

      const transferIx = SystemProgram.transfer({
        fromPubkey: vaultPda,
        toPubkey: recipient,
        lamports: Number(transferAmount),
      });

      const action = {
        programId: SystemProgram.programId,
        accounts: [
          { pubkey: vaultPda, isWritable: true },
          { pubkey: recipient, isWritable: true },
        ],
        data: Buffer.from(transferIx.data),
      };

      await program.methods
        .createOrder(
          inputAmount,
          trigger,
          action,
          null, // expires_slot
          executionBounty
        )
        .accounts({
          user: user.publicKey,
          orderCounter: orderCounterPda,
          order: orderPda,
          vault: vaultPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([user])
        .rpc();

      // Verify order account
      const orderAccount = await (program.account as any).order.fetch(orderPda);
      expect(orderAccount.user.equals(user.publicKey)).to.be.true;
      expect(orderAccount.orderId.toNumber()).to.equal(0);
      expect(orderAccount.inputAmount.toString()).to.equal(
        (2n * LAMPORTS_PER_SOL).toString()
      );
      expect(orderAccount.executed).to.be.false;
      expect(orderAccount.canceled).to.be.false;

      // Verify vault has lamports
      const vaultAccount = await provider.connection.getAccountInfo(vaultPda);
      expect(vaultAccount).to.not.be.null;
      expect(vaultAccount!.lamports).to.be.at.least(Number(2n * LAMPORTS_PER_SOL));

      // Verify counter incremented
      const counterAccount = await (
        program.account as any
      ).userOrderCounter.fetch(orderCounterPda);
      expect(counterAccount.nextOrderId.toNumber()).to.equal(1);
      expect(counterAccount.openOrderCount.toNumber()).to.equal(1);
    });
  });

  // create the keeper account

  let keeper: Keypair;
  let latestBlockHash: any;

  before(async () => {
    // create the keeper account before tests run
    latestBlockHash = await provider.connection.getLatestBlockhash();
    keeper = Keypair.generate();
    const sig = await provider.connection.requestAirdrop(
      keeper.publicKey,
      10 * Number(LAMPORTS_PER_SOL)
    );
    await provider.connection.confirmTransaction({
      signature: sig,
      blockhash: latestBlockHash.blockhash,
      lastValidBlockHeight: latestBlockHash.lastValidBlockHeight,
    });
  });
 

  describe("execute_order_if_ready", () => {
    it("executes order if ready successfully", async () => {
      
      const recipient = provider.wallet.publicKey;
      const recipientBalanceBefore = await provider.connection.getBalance(recipient);
      console.log("recipient (CLI wallet) balance before", recipientBalanceBefore);


      const keeperBalanceBefore = await provider.connection.getBalance(keeper.publicKey);
      console.log("keeper balance", keeperBalanceBefore);
      expect(keeperBalanceBefore).to.equal(10 * Number(LAMPORTS_PER_SOL));

      

      const [orderPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("order"), user.publicKey.toBuffer(), Buffer.alloc(8, 0)],
        program.programId
      );

      const [vaultPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("vault"), user.publicKey.toBuffer(), Buffer.alloc(8, 0)],
        program.programId
      );

      // check the vault balance (2 SOL + rent-exempt min for 0-byte account ~890880)
      const vaultBalance = await provider.connection.getBalance(vaultPda);
      console.log("vault balance", vaultBalance);
      const expectedVaultBalance = Number(2n * LAMPORTS_PER_SOL) + 890880; // 2 SOL + rent
      expect(vaultBalance).to.equal(expectedVaultBalance);

      // CPI remaining_accounts: [vault, recipient, system_program] per CpiAction layout
      // User pays the tx fee (not recipient); build tx with user as fee payer
      const executeIx = await program.methods
        .executeOrderIfReady()
        .accounts({
          order: orderPda,
          vault: vaultPda,
          user: user.publicKey,
          keeper: keeper.publicKey,
          pdaAccount: SystemProgram.programId, // placeholder for TimeAfter trigger
          systemProgram: SystemProgram.programId,
        })
        .remainingAccounts([
          { pubkey: vaultPda, isWritable: true, isSigner: false },
          { pubkey: provider.wallet.publicKey, isWritable: true, isSigner: false },
          { pubkey: SystemProgram.programId, isWritable: false, isSigner: false },
        ])
        .instruction();

      const tx = new Transaction().add(executeIx);
      tx.feePayer = user.publicKey;
      await sendAndConfirmTransaction(provider.connection, tx, [user, keeper], {
        preflightCommitment: "confirmed",
      });


      // verifications 

       
      // verify the order pda is in the right state
      const orderAccount = await (program.account as any).order.fetch(orderPda);
      // Log all fields from the order PDA account
      console.log("Order PDA fields:");
      console.log("user:", orderAccount.user.toBase58());
      console.log("order_id:", orderAccount.orderId?.toString());
      console.log("input_amount:", orderAccount.inputAmount?.toString());
      console.log("trigger:", orderAccount.trigger);
      console.log("action:", orderAccount.action);
      console.log("created_slot:", orderAccount.createdSlot?.toString());
      console.log("expires_slot:", orderAccount.expiresSlot ? orderAccount.expiresSlot.toString() : null);
      console.log("executed:", orderAccount.executed);
      console.log("canceled:", orderAccount.canceled);
      console.log("execution_bounty:", orderAccount.executionBounty?.toString());
      expect(orderAccount.executed).to.be.true;


      // verify vault decreased by 1 SOL (transfer) + execution bounty
      const vaultBalanceAfter = await provider.connection.getBalance(vaultPda);
      console.log("vault balance", vaultBalanceAfter);
      const bounty = Number(orderAccount.executionBounty?.toString() ?? 0);
      expect(vaultBalanceAfter).to.equal(vaultBalance - Number(LAMPORTS_PER_SOL) - bounty);

      // verify the recipient received exactly 1 SOL (user pays tx fee, not recipient)
      const recipientBalanceAfter = await provider.connection.getBalance(recipient);
      console.log("recipient (CLI wallet) balance after", recipientBalanceAfter);
      expect(recipientBalanceAfter).to.equal(recipientBalanceBefore + Number(LAMPORTS_PER_SOL));

      // verify the keeper balance has increased by the execution bounty
      const keeperBalanceAfter = await provider.connection.getBalance(keeper.publicKey);
      console.log("keeper balance after", keeperBalanceAfter);
      expect(keeperBalanceAfter).to.be.at.least(Number(keeperBalanceBefore) + Number(orderAccount.executionBounty?.toString()));

      
    });
  });
});
