[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
order_executor = "2f2ph1Sgi14dAfKwYXNb5XPuAhuokWCW5WNLyfiQXKc2"

[programs.localnet]
order_executor = "3p8QPys3SHaEyf4szGgcoF4x2FbGaT3uTgZibLity5hi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
